name: Test
on: 
	push:
		branches:
			- main

jobs:
	test:
		- name: Checkout repository
    - uses: actions/checkout@v3
    
		- name: Install dependencias
		- run: npm install

		- name: Run test
		- run: npm test 
